apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-sf-deploy-test
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: init
  name: init
spec:
  containers:
    - args:
        - -c
        - airflow list_users || (airflow initdb && airflow create_user --role Admin --username airflow --password airflow -e airflow@airflow.com -f airflow -l airflow)
      command:
        - /bin/bash
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: CeleryExecutor
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            configMapKeyRef:
              name: apache-airflow-config
              key: sql_alchemy_conn
          #value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - name: AIRFLOW__WEBSERVER__RBAC
          value: "True"
      image: docker.io/thescomcontainers/airflow:1.0.0
      name: init
      resources: {}
  restartPolicy: OnFailure
  status: {}
