apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  secretStoreRef:
    name: ibmcloud-secrets-manager
    kind: SecretStore
  target:
    name: external-secret
  data:
    - secretKey: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      remoteRef:
        key: kv/6599c459-c779-87b1-fe1a-a074f10be624
        property: AIRFLOW__CORE__SQL_ALCHEMY_CONN
    - secretKey: AIRFLOW__CELERY__FLOWER_BASIC_AUTH
      remoteRef:
        key: kv/57020dfe-bf8a-dac8-36e9-1a2ea537931e
        property: AIRFLOW__CELERY__FLOWER_BASIC_AUTH
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: kv/ed242008-a956-9ddb-755f-0c737ce39e7b
        property: POSTGRES_PASSWORD
    - secretKey: AIRFLOW__CELERY__RESULT_BACKEND
      remoteRef:
        key: kv/140a01b4-da30-af7b-6627-88414254b39f
        property: AIRFLOW__CELERY__RESULT_BACKEND
