apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  secretStoreRef:
    name: ibmcloud-secrets-manager
    kind: SecretStore
  target:
    name: external-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: kv/fbfd18d0-a869-3afe-f06e-93c37421aeb3
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: kv/689c8235-ab22-66a6-a778-b99bfb523eb5
        property: POSTGRES_USER
    - secretKey: POSTGRES_DB
      remoteRef:
        key: kv/9121681b-eb65-ce45-3415-acb639c04f85
        property: POSTGRES_DB
    - secretKey: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      remoteRef:
        key: kv/e2e62508-f286-9d74-d610-4a2d6d99eeec
        property: AIRFLOW__CORE__SQL_ALCHEMY_CONN
    - secretKey: AIRFLOW__CELERY__RESULT_BACKEND
      remoteRef:
        key: kv/3925ce3d-d330-ad01-8fd0-c4bb41ebce14
        property: AIRFLOW__CELERY__RESULT_BACKEND
    - secretKey: AIRFLOW__CELERY__FLOWER_BASIC_AUTH
      remoteRef:
        key: kv/a79cb6d3-ccc8-57d5-5707-5c2b525ca01b
        property: AIRFLOW__CELERY__FLOWER_BASIC_AUTH
    - secretKey: FERNET_KEY
      remoteRef:
        key: arbitrary/1441ff03-3198-431f-d408-97f529c6ba40
        property: FERNET_KEY