apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  secretStoreRef:
    name: ibmcloud-secrets-manager
    kind: SecretStore
  target:
    name: external-secret
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: kv/3552c1e5-0234-84be-89ce-b845490c9f3e
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: kv/83d4a198-f059-f283-8c47-4ce617048c64
        property: POSTGRES_USER
    - secretKey: POSTGRES_DB
      remoteRef:
        key: kv/9121681b-eb65-ce45-3415-acb639c04f85
        property: POSTGRES_DB
    - secretKey: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      remoteRef:
        key: kv/aa290491-954a-12b3-4912-67b1bf7ebb94
        property: AIRFLOW__CORE__SQL_ALCHEMY_CONN
    - secretKey: AIRFLOW__CELERY__RESULT_BACKEND
      remoteRef:
        key: kv/a8be5c0a-f2c7-1861-9799-36bb8f0a7f15
        property: AIRFLOW__CELERY__RESULT_BACKEND
    - secretKey: AIRFLOW__CELERY__FLOWER_BASIC_AUTH
      remoteRef:
        key: kv/a79cb6d3-ccc8-57d5-5707-5c2b525ca01b
        property: AIRFLOW__CELERY__FLOWER_BASIC_AUTH
    - secretKey: FERNET_KEY
      remoteRef:
        key: arbitrary/1441ff03-3198-431f-d408-97f529c6ba40
        property: FERNET_KEY
