apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: flower
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flower
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: flower
    spec:
      serviceAccountName: airflow-scheduler
      containers:
        - args:
            - flower
          env:
            - name: EXECUTOR
              value: Celery
            - name: REDIS_PASSWORD
              value: redispass
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: sql_alchemy_conn
            - name: AIRFLOW__CORE__EXECUTOR
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: executor
          image: docker.io/thescomcontainers/airflow:1.0.0
          name: flower
          command: [
              "sh",
              "-c",
              "airflow list_users || (airflow db init
              && airflow create_user --role Admin --username airflow --password airflow -e airflow@airflow.com -f airflow -l airflow)",
            ]
          ports:
            - containerPort: 5555
          resources: {}
      restartPolicy: Always
status: {}
