kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: dev-sf-deploy-test
spec:
  type: NodePort
  selector:
    deploy: postgres
    name: postgres
    component: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
