apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRESQL_DATABASE
              value: airflow
            - name: POSTGRESQL_PASSWORD
              value: airflow
            - name: POSTGRESQL_USER
              value: airflow
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: airflow
          image: quay.io/centos7/postgresql-13-centos7
          name: postgres
          resources: {}
      restartPolicy: Always
status: {}
