kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webserver
  namespace: dev-sf-deploy-test
  labels:
    app.kubernetes.io/instance: airflow-yamls-test
    io.kompose.service: webserver
spec:
  host: >-
    ibm-sf-airflow-webserver.devsfcluster-56118b4b985711fc98241a723e4ef72a-0000.eu-de.containers.appdomain.cloud
  to:
    kind: Service
    name: webserver
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIF1jCCBL6gAwIBAgISBOl06yjKquVUPDR6FjG4WLkuMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMzA2MTkwMzIwMDdaFw0yMzA5MTcwMzIwMDZaMDgxNjA0BgNVBAMT
      LWRldnNmY2x1c3Rlci5ldS1kZS5jb250YWluZXJzLmFwcGRvbWFpbi5jbG91ZDCC
      ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKYutSbu6hdcUu27tHydk0gs
      Vy0cvLh3ti2rtvOn3hvbnkuGT+reOigW0bR1Yi2E0/dRZAUTihxMzfSX23ZAnHOy
      TOP3MJl9MFHjCqia410X6vwDuzHKcj9liSd/tE2oZUzV+j847ApxrnV2Sf64eHM2
      bUfk4r9E9SRi2JxPzvoue3p6xoDDWOEimTBC2Qxb85T+gunR8+5EKHNwm2YpE/mF
      2UNqWbGBaz/BFl116tnK6FYiJHT+ZLwaCrr+vZAeRbZC7wMWw1KKINr1npe1gQtJ
      kDnQES+tFg/pgK3SkPOwsIWcRNHQdIFRuPe80BKTrvwf7YGRKl2dW1aLaeDTrGcC
      AwEAAaOCAt4wggLaMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcD
      AQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUCmrPQQ5T7KuieGUf
      ZQ4aNTyVRKcwHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYB
      BQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYI
      KwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wgeYGA1UdEQSB3jCB24JV
      Ki5kZXZzZmNsdXN0ZXItNTYxMThiNGI5ODU3MTFmYzk4MjQxYTcyM2U0ZWY3MmEt
      MDAwMC5ldS1kZS5jb250YWluZXJzLmFwcGRvbWFpbi5jbG91ZIJTZGV2c2ZjbHVz
      dGVyLTU2MTE4YjRiOTg1NzExZmM5ODI0MWE3MjNlNGVmNzJhLTAwMDAuZXUtZGUu
      Y29udGFpbmVycy5hcHBkb21haW4uY2xvdWSCLWRldnNmY2x1c3Rlci5ldS1kZS5j
      b250YWluZXJzLmFwcGRvbWFpbi5jbG91ZDATBgNVHSAEDDAKMAgGBmeBDAECATCC
      AQQGCisGAQQB1nkCBAIEgfUEgfIA8AB2AHoyjFTYty22IOo44FIe6YQWcDIThU07
      0ivBOlejUutSAAABiNHhqowAAAQDAEcwRQIgNO74Zf9xeDyQSeg8TaYSHh7TF4TP
      jvAwKWql2y7Y5vECIQDCYSvl6J5eV10ND8dAEK0QX/DaV7MroMSyjcw18JkWdQB2
      AOg+0No+9QY1MudXKLyJa8kD08vREWvs62nhd31tBr1uAAABiNHhqrEAAAQDAEcw
      RQIgabpKWnr8JYP0EB8q7R23vRa4EHvRCWG6ZHhdHe0Ov4cCIQCXFS8yV9HQmHsi
      cIMIyM+fz7+t/W+PPLcbavIkbBTprDANBgkqhkiG9w0BAQsFAAOCAQEARs2O4x4O
      JmrsXfHtmEThorh7Oc5JTiWHNOULgUebmO8oWde5zV5lNRWRlUuSck8zsJTg4xMd
      NJaenvm6Gmf1thXiJJSJwu3uvDUumPvqTtTlUZLIFRnAQcYhX97p9jGZMNjBoRQR
      qJgAPWnbUOJiLMk+kSsMbeypsvPiT5P+IW39KPpjW5ZT/S6Ak4MD6kBp9etdadpF
      XfAnweEe16wgJdWBQPN/qJK3Vp8L61jBNRbxnky+2ZY6Hxx6OLIi3IfajAUBhioB
      +RCVNQywLt1HLHRe8myfl6tYtu+eXoWX+NpI6O+0MhHq1grSJLLUDmfG0+oiScHg
      bisSMCiFl3TNLA==
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/      
      MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
      DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
      ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
      wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
      LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
      4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
      bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
      sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
      Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
      FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
      SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
      PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
      TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
      SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
      c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
      +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
      ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
      b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
      U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
      MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
      5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
      9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
      WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
      he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
      Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEApi61Ju7qF1xS7bu0fJ2TSCxXLRy8uHe2Lau286feG9ueS4ZP
      6t46KBbRtHViLYTT91FkBROKHEzN9JfbdkCcc7JM4/cwmX0wUeMKqJrjXRfq/AO7
      McpyP2WJJ3+0TahlTNX6PzjsCnGudXZJ/rh4czZtR+Tiv0T1JGLYnE/O+i57enrG
      gMNY4SKZMELZDFvzlP6C6dHz7kQoc3CbZikT+YXZQ2pZsYFrP8EWXXXq2croViIk
      dP5kvBoKuv69kB5FtkLvAxbDUoog2vWel7WBC0mQOdARL60WD+mArdKQ87CwhZxE
      0dB0gVG497zQEpOu/B/tgZEqXZ1bVotp4NOsZwIDAQABAoIBADnikx8YoVm5wvkk
      JN4zVRYSu9ru452ttTt7UKLWmjtB6IWOJ1A8UC2epTUiniwU1HCVXS2XfMgWyLam
      Hr+2CckTFk1h0P/l52reltvb9855glR+SDoztk/24itsBDX4rjBxaFWVUkLhDk/E
      AEpFn08iajZct87AClO+So1ID2R9NKuAdma4FZWdVRI/W/OSEGY+3Nkqob6VpyPp
      JRnkR0nh/vBaSJ7XQ73CU5ZBY2I95wawG1/GXt7/JN4oBdYEF5/Iv++mgpJ7EoyF
      +WU7w4QotWSqi0Vw5pNJt7JhdEjhM/lNYAavbkLFmlpHKd30FKSTOllnLk6Pvnvw
      aylYU0ECgYEA1KYQ7YLMvwohTHiyZextJWt6rtS5fgNFf4UC9m/o8/iWY2AyrW+k
      de0ZcDs7zO4tIWQPpc+vx3CFh1VNTZV5KUlzRVy3riMgPnIs0CWmRgLML88aLnfC
      WPNK+RYoq7mHYicRzHGdT/o3w8nLbaHsU7gTXpyzPGbZ3Wu7B0aDSG8CgYEAyA+c
      vTwQCBRtPaZVkolqEr7O1v9vc2/p06motb/Sv/wqhziRJu3YzW7vw6SpKjckMy3r
      5PdgTaiL5vczKh0S27KPVzKoQ8fdYVCZus6WPgoaIpaU3xXNFoKTjRBciB9R7+q0
      Whi0GLSiCrZWLVENbB/wwj+Yiemv7CKJ+C6HJ4kCgYANUCRJKmI1J6Y0Cm5o0Sd4
      K0VwAqNmT0Afnq0zzofQFmUb7Z7emtm6BFEOZLb2uoaay4/rOphvrQy/D0karVv7
      iLytwAND5LEVF8LUeTbytSQhbh7ef+Lr/LdZ5tg/AAuIypdjrE1D/49UM6MHxxZr
      m1+jEb5q7ql/IkqARxrbAwKBgGsbqK/Li024GfBKsD++4BJfI4AJy5KDFS3kBFYh
      9+QfTmmMyHGOH2eFAEq/Sm42jWP1Lvkr09xf417pc/QVEraat5FYpqt7QrPKIjPY
      TKm0YN+pvNRe6KkniXWZj+C02/pVru8ZkLo1YxfXHPYwEb6UryJgR/t2KGCE8Vb1
      Ghj5AoGBAJgQz36OtUchIv5V6SpsKUHMKqctSb5VdpeOhN0NE3gh5JhrhIRyZQ59
      1zDg1gjQsh7d/D1X4JcIWbF1Q6ZiDRHAqkR97F9udfPHSmH7uV+MAQ0omRiZWAms
      z09NR9Lzdjr429Bmv4sBymxBXVi1BZG24U4MLBgG8w1MuXT4M9mA
      -----END RSA PRIVATE KEY-----
  wildcardPolicy: None
status:
  ingress:
    - host: >-
        ibm-sf-airflow-webserver.devsfcluster-56118b4b985711fc98241a723e4ef72a-0000.eu-de.containers.appdomain.cloud
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
      routerCanonicalHostname: >-
        router-default.devsfcluster-56118b4b985711fc98241a723e4ef72a-0000.eu-de.containers.appdomain.cloud


