kind: ServiceAccount
apiVersion: v1
metadata:
  name: apache-airflow-scheduler
  labels:
    tier: airflow
    component: scheduler
    release: release-name
    chart: "airflow-1.5.0"
    heritage: Helm
