apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ibmcloud-secrets-manager
spec:
  provider:
    ibm:
      serviceUrl: https://5a080c2c-e77f-48ff-83f2-a0d6e0a68183.eu-de.secrets-manager.appdomain.cloud
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: secret-api-key
            key: apiKey
