kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow
  namespace: "dev-sf-deploy-test"
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: airflow
      name: airflow
      component: webserver
  template:
    metadata:
      labels:
        deploy: airflow
        name: airflow
        component: webserver
    spec:
      serviceAccountName: airflow-scheduler
      containers:
        - name: airflow-scheduler
          image: "docker.io/thescomcontainers/airflow:1.0.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: sql_alchemy_conn
            - name: AIRFLOW__CORE__EXECUTOR
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: executor
            - name: REDIS_PASSWORD
              value: redispass
          volumeMounts:
            - name: dags-pv
              mountPath: /usr/local/airflow/dags
            - name: logs-pv
              mountPath: /usr/local/airflow/logs
            - name: spark_scripts-pv
              mountPath: /usr/local/airflow/spark_scripts
            - name: downloads-pv
              mountPath: /usr/local/airflow/downloads
            - name: plugins-pv
              mountPath: /usr/local/airflow/plugins
          command:
            - airflow
          args:
            - scheduler
        - name: airflow-webserver
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: sql_alchemy_conn
            - name: AIRFLOW__CORE__EXECUTOR
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: executor
          image: "apache/airflow:2.2.4"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          command:
            - airflow
          args:
            - webserver
      restartPolicy: Always
      volumes:
        - name: dags-pv
          persistentVolumeClaim:
            claimName: dags-pvc
        - name: logs-pv
          persistentVolumeClaim:
            claimName: logs-pvc
        - name: plugins-pv
          persistentVolumeClaim:
            claimName: plugins-pvc
        - name: downloads-pv
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: spark_scripts-pv
          persistentVolumeClaim:
            claimName: spark_scripts-pvc
