apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
    spec:
      containers:
        - env:
            - name: EXECUTOR
              value: Celery
            - name: FERNET_KEY
              value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - name: LOAD_EX
              value: "n"
            - name: POSTGRES_DB
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_ADMIN_PASSWORD
              value: airflow
            - name: REDIS_PASSWORD
              value: redispass
          image: jpacerqueira83/docker_airflow:latest
          name: webserver
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: webserver-claim0
            - mountPath: /usr/local/airflow/plugins
              name: webserver-claim1
            - mountPath: /usr/local/airflow/spark_scripts
              name: webserver-claim2
            - mountPath: /usr/local/airflow/downloads
              name: downloads
      restartPolicy: Always
      volumes:
        - name: webserver-claim0
          persistentVolumeClaim:
            claimName: webserver-claim0
        - name: webserver-claim1
          persistentVolumeClaim:
            claimName: webserver-claim1
        - name: webserver-claim2
          persistentVolumeClaim:
            claimName: webserver-claim2
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
status: {}
