apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
  namespace: dev-sf-deploy-test
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: postgres:9.6
      generation: null
      importPolicy: {}
      name: "9.6"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
