apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: jpacerqueira83/docker_airflow:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
