apiVersion: apps/v1
kind: StatefulSet
#kind: Deployment
#kind: Job
metadata:
  name: git-sync-test
spec:
  selector:
    matchLabels:
      app: git-sync-test
  serviceName: "git-sync-test"
  replicas: 1
  template:
    metadata:
      labels:
        app: git-sync-test
    spec:
      containers:
      - name: git-sync-test
        image: docker.io/thescomcontainers/airflow:2.1.10
        volumeMounts:
        - name: service
          mountPath: /var/magic
      initContainers:
      - name: git-sync
        image: k8s.gcr.io/git-sync-amd64:v2.0.6
        imagePullPolicy: Always
        volumeMounts:
        - name: service
          mountPath: /magic
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/FD-Data-Engineering/sf-airflow.git
        - name: GIT_SYNC_BRANCH
          value: test
        - name: GIT_SYNC_ROOT
          value: /usr/local/airflow
        - name: GIT_SYNC_DEST
          value: daga
        - name: GIT_SYNC_PERMISSIONS
          value: "0777"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_PERIOD
          value: "10"
      volumes:
      - name: service
        emptyDir: {}
      - name: git-secret
        secret:
          defaultMode: 256
          secretName: git-credsc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDQVFDL2pzeTdMVFdGbkxobWg5VjVHWXVua2VkcXNPbnFtd2RRUGV0dFlQS2VOLzVHK05OYWJmN2VhNDJLbER6L3JZbmNleHZKZ3FmNjJVb1hMMGZSME4vZHlBcFp3dG03RUdtZzNCN2N0VlRmN01WQVJidGYwcVhDTUdubXdQaTBLQTZuNml0dkxvbkpWb2hpbi9BTDB0bmR2VjM0VTBPbCtTUnBhSmI1VjhQRWpQQmNuT2lqd1UyTFdnNTQybmxXanJ0N1VYd1V6VWpCTTVhcC9FVDl5NjdaSXh1ek5VTWU4TTZMMEdXRW54OFFtaERjQ1Z3dklQODlsM1ZUWm80WHoyaC9sTHNUeEFCNmE4UmlNQnNSL01GY3FqVm5YTlJUKy9UVGY4dm8xeW1iR1NkR0pYdy9iNWNGcEdTVEd3MmxFVGVtcmthWksrREZDanZhaW5NajdZb2pMaktXVG1NYWQ3dU1YajBWOXhqTFZTN1UwaHFybGZOWWFWN04rQVpYSjZlaERuMU5pNjBpMnRuTUtnT1BIOGhvZlZuZWtsWGhKVE5Qb2EzWWVVUUNzbGc0STlqZ2QzSUlkZVNYQ1JpNmZocXhHUmhCQ1k1YnArc2sySHM5dXpPdDRMZjVKQlduZE16dVFreTJOQUNlYUtvWGxOQ2pQTlRyd0M1OWdhQ3Z6MU03KzQ1S1hsSGIwTWtEbGU4RjlqOC8wQllEQzB3Y3RiZUZ6eHd4elBaektDT3F0VCtBWjFrN3F4TDFNTzhKUk9OeVByNzBqODB4OGRXbUUyc1VXNk9OZlFnRjNYVFJlaFloSDFiWHptVC83Z3pRN1IyQWRkZTNITnRiQTBwYWxML2Y1TnJucFRqMlVWZjdzTVFxWXR2dUZVNHIyYU5scU0rbEdUUU9UMkg2Tnc9PSBtY3AwMjFAZW1haWwuY29tCg== # your-ssh-key
executor: CeleryExecutor
enablePodLaunching: true