apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  namespace: dev-sf-deploy-test
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 3
  template:
    metadata:
      labels:
        app: httpd
    spec:
      securityContext:
        runAsUser: 1000720000
      containers:
        - name: httpd
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          ports:
            - containerPort: 8080
